### PR TITLE
Implemented search functionality

### LINKED ISSUE #2: [Feature] - Search for movies/shows
For example:
`nrkdl search "someshow"`

### PR DESCRIPTION
**Pull request by runarmod**
Search using cmd arg. Choose season/episode with arg or later.

Fixes #2

### CODE REVIEW

**Comment by runarmod** [comment]
This also handles KeyboardInterrupt and EOFError when typing Ctrl+C/Z during download/search.

**Comment by jenslys** [comment]
Look good, but missing changes in README to reflect changes

**Comment by runarmod** [comment]
Should be fixed now

**Comment by jenslys** [comment]
LGTM 👍🏻

**Pull request merged**
